name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9

    - name: Terraform Init
      run: terraform init

#     - name: Terraform Apply
#       if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
#       run: terraform apply -auto-approve -input=false
